#!/usr/bin/env python
# coding: UTF-8

import sys
from task import task


t = task()

if len(sys.argv) < 2:
    t.build()
    t.show()
    sys.exit()

options = sys.argv

if options[1] == "add":
    t.add(options[2])
elif options[1] == "show":
    t.show()
elif options[1] == "delete":
    t.delete(options[2])
else:
    print "Error input"
