#!/bin/python
# coding: UTF-8

import sys
import os

# 博客目录
blog_dir = '/home/svitter/svtter.github.io/source/_posts'

if len(sys.argv) < 2:
    print 'no option'
else:
    if sys.argv[1].startswith('-'):
        # 改变工作目录
        os.chdir(blog_dir)
        option = sys.argv[1][1:]
        if option == 'n':
            os.system("hexo n " + sys.argv[2])
            os.system("gvim " + sys.argv[2] + ".md")
        elif option == 'g':
            os.system('hexo gm')
            os.system('hexo d')
        else:
            print 'no such command.'
