#!/bin/bash

echo "input what you want: "
echo "1. add new dairy"
echo "2. change today dairy"
echo "3. change yestorday dairy"
echo "0. edit cmd dairy"

read op
if [ $op = 0 ]; then
    vim ~/bin/dairy
elif [ $op = 1 ]; then
    $bin/lib/dairy/add_dairy
    echo "success."
elif [ $op = 2 ]; then
    $bin/lib/dairy/edit_dairy
    echo "success."
elif [ $op = 3]; then
    cd $PLAN
else
    echo "no command."
fi
    

