#!/bin/bash

# plugin list
export plugin=$profile/plugin
. $plugin/ACM               # ACM
. $plugin/blog              # blog
. $plugin/dairy             # dairy
. $plugin/dictionary        # dairy
. $plugin/file              # file
. $plugin/git               # file
. $plugin/python-settings   # python
. $plugin/special_g++       # special g++
# . $profile/plugin/temp              # special g++
# mark website
. $plugin/mark              
. $plugin/work
. $plugin/java

unset plugin
