#!/bin/bash

# plugin list
. $profile/plugin/ACM               # ACM
. $profile/plugin/blog              # blog
. $profile/plugin/dairy             # dairy
. $profile/plugin/dictionary        # dairy
. $profile/plugin/file              # file
. $profile/plugin/git               # file
. $profile/plugin/python-settings   # python
. $profile/plugin/special_g++       # special g++
# . $profile/plugin/temp              # special g++
# mark website
. $profile/plugin/mark              
