#!/bin/bash

# build a simple server
function server
{
    python -m SimpleHTTPServer 8080
}

# start server
function workers
{
    sudo systemctl start httpd.service
    sudo systemctl start mysqld.service
}
